### ISSUE TITLE
Error: Call to a member function getValue() on null

### ISSUE THREAD

**Issue by paragonn** [putyourlightson/craft-secrets#1]
### Question
Receiving the following error message:
Error: Call to a member function getValue() on null in /sites/bsc-delve/vendor/putyourlightson/craft-secrets/src/Secrets.php:39

### Additional context
1. I installed and enabled the plugin
2. I successfully created a Secrets key-value pair
3. I added the following code to the db.php:

use putyourlightson\secrets\Secrets;

return [
    'driver' => getenv('DB_DRIVER'),
    'server' => getenv('DB_SERVER'),
    'user' => getenv('DB_USER'),
    // 'password' => getenv('DB_PASSWORD'),
    'password' => Secrets::getValue('dbPass'),
    'database' => getenv('DB_DATABASE'),
    'schema' => getenv('DB_SCHEMA'),
    'tablePrefix' => getenv('DB_TABLE_PREFIX'),
    'port' => getenv('DB_PORT')
];

When I visit the website in the browser that is when I see the error message.

Thanks for the plugin and any help would be appreciated!

**Comment by paragonn** [comment]
A gentle nudge on the issue described above. Thanks!

**Comment by bencroker** [comment]
Sorry for not responding sooner, this went under my radar, somehow.

It looks like you’re calling `Secrets::getValue` before Craft has been initialised, which, since it is a plugin and must be registered before being used, this is not going to work here.
